# Generated by Django 4.0.3 on 2022-04-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foruns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='tags',
        ),
    ]
