# Generated by Django 4.0.3 on 2022-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Game')),
                ('about', models.TextField(verbose_name='Sobre o jogo')),
                ('distributor', models.CharField(max_length=100, verbose_name='Distribuidor')),
                ('developer', models.CharField(max_length=100, verbose_name='Desenvolvedora')),
                ('date_lauch', models.IntegerField(verbose_name='data de lançamento')),
                ('image', models.ImageField(upload_to='game_img/%Y/%m/%d')),
            ],
        ),
    ]
