# Generated by Django 4.0.3 on 2022-04-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='distributor',
            field=models.CharField(max_length=100, verbose_name='Distribuidora'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='game_img/%Y/%m/%d', verbose_name='Imagem'),
        ),
    ]
