# Generated by Django 4.0.3 on 2022-04-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_game_date_lauch_alter_game_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='mkmkkmk', max_length=20, verbose_name='Descrição do jogo'),
            preserve_default=False,
        ),
    ]
