# Generated by Django 4.0.3 on 2022-04-30 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_rename_message_contact_alter_comment_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Jogar Depois'), ('2', 'Não Gostei'), ('3', 'Jogando'), ('4', 'Dropado'), ('5', 'Jogados zerados')], max_length=20, verbose_name='status')),
                ('favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de adição')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Jogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
