# Generated by Django 4.0.3 on 2022-05-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_gameuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='status',
            field=models.CharField(choices=[('0', 'vazio'), ('1', 'Jogar Depois'), ('2', 'Não Gostei'), ('3', 'Jogando'), ('4', 'Dropado'), ('5', 'Jogos zerados')], max_length=20, verbose_name='status'),
        ),
    ]
